# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c096c049614064c3ad7184e028abdb34731c2f10eca90f87b46de4a86bdc389cc77f028c04d021c99f43ba65e45b23ad0eed3234b3bb9ff40378de95fab0ee

test:
  secret_key_base: d896d5600601d5b93691fbfd30692da67fd4dc5a5327235033a7ebf863a1d662af4e954f36b819d6624e978a225e3a1c278c980944e8a1ca0819db01d0f8f154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
